---
development:
  cloud_name: dt8tllzzd
  api_key: '992573219328542'
  api_secret: vweQ0Z_yIT5DHbrbkx8fMFIKusk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dt8tllzzd
  api_key: '992573219328542'
  api_secret: vweQ0Z_yIT5DHbrbkx8fMFIKusk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dt8tllzzd
  api_key: '992573219328542'
  api_secret: vweQ0Z_yIT5DHbrbkx8fMFIKusk
  enhance_image_tag: true
  static_image_support: false
